<a href="https://colab.research.google.com/github/Malicef/Sistemas-Inteligentes-projeto1/blob/main/Modelo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import kagglehub
import pandas as pd

In [9]:
dados = pd.read_csv('Power Plant Data.csv')
dados.head()

      AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

1. Calcule a correlação entre as variáveis independentes (AT, V, AP, RH) e a variável dependente (PE). Quais
variáveis parecem ter maior influência na produção de energia?

In [11]:
correlacoes = dados[["AT", "V", "AP", "RH", "PE"]].corr()["PE"]
correlacoes

AT   -0.948128
V    -0.869780
AP    0.518429
RH    0.389794
PE    1.000000
Name: PE, dtype: float64

2. Calcule a correlação entre as variáveis independentes (AT, V, AP, RH) entre si. Existe alguma relação forte
entre elas? Se sim, isso pode indicar multicolinearidade.

In [12]:

dados.corr()

          AT         V        AP        RH        PE
AT  1.000000  0.844107 -0.507549 -0.542535 -0.948128
V   0.844107  1.000000 -0.413502 -0.312187 -0.869780
AP -0.507549 -0.413502  1.000000  0.099574  0.518429
RH -0.542535 -0.312187  0.099574  1.000000  0.389794
PE -0.948128 -0.869780  0.518429  0.389794  1.000000

3. Construa um modelo de regressão linear múltipla utilizando as variáveis independentes (AT, V, AP, RH)
para prever a variável dependente (PE). Divida os dados em treino (80%) e teste (20%).

In [13]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression

In [14]:
entrada = dados.drop(columns=["PE"])
saida = dados["PE"]

In [15]:
scaler  = MinMaxScaler(feature_range=(0, 1))
padronizados  = scaler.fit_transform(dados)
dados_padronizados = pd.DataFrame(padronizados, columns=dados.columns)
dados_padronizados

            AT         V        AP        RH        PE
0     0.372521  0.291815  0.771591  0.638204  0.569536
1     0.662040  0.669039  0.671863  0.449330  0.319338
2     0.093484  0.249822  0.476862  0.892493  0.904636
3     0.539660  0.568683  0.429349  0.684718  0.347285
4     0.255241  0.216014  0.404355  0.952547  0.710464
...        ...       ...       ...       ...       ...
9563  0.420397  0.432918  0.522643  0.877212  0.526755
9564  0.322380  0.245907  0.761693  0.552547  0.653775
9565  0.835977  0.871352  0.495669  0.146381  0.123311
9566  0.642210  0.784520  0.518931  0.493700  0.205033
9567  0.560623  0.661210  0.602326  0.567158  0.437351

[9568 rows x 5 columns]

In [16]:
entrada_treino, entrada_teste, saida_treino, saida_teste = train_test_split(entrada, saida, test_size=0.3, random_state=42)

print(f"Tamanho do dataset = {dados.shape[0]} amostras")
print(f"Quantidade de amostras de treinamento = {entrada_treino.shape[0]} amostras")
print(f"Quantidade de amostras de teste = {entrada_teste.shape[0]} amostras")

Tamanho do dataset = 9568 amostras
Quantidade de amostras de treinamento = 6697 amostras
Quantidade de amostras de teste = 2871 amostras

In [17]:
modelo = LinearRegression()
modelo.fit(entrada_treino, saida_treino)

LinearRegression()

4. Avalie o desempenho do modelo utilizando métricas como R², RMSE e MAE. O modelo é adequado para
prever a produção de energia? Justifique sua resposta.

In [18]:
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [19]:
saida_pred = modelo.predict(entrada_teste)

In [20]:
mse = mean_squared_error(saida_teste, saida_pred)
r2 = r2_score(saida_teste, saida_pred)
mae = mean_absolute_error(saida_teste, saida_pred)


print(f"Erro quadrático médio (MSE): {mse:.2f}")
print(f"Coeficiente de determinação (R²): {r2:.2f}")
print(f"Erro médio absoluto (MAE): {mae:.2f}")

Erro quadrático médio (MSE): 21.24
Coeficiente de determinação (R²): 0.93
Erro médio absoluto (MAE): 3.65