<a href="https://colab.research.google.com/github/Malicef/Sistemas-Inteligentes-projeto1/blob/main/Usinas_de_ciclo_combinado.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import kagglehub
import pandas as pd

In [10]:
dados = pd.read_csv('Power Plant Data.csv')
dados.head()

      AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

O dataset contem 9.568 amostras coletadas ao longo de 6 ano

In [11]:
n_features = dados.shape[1]
print(f"\nNúmero de features: {n_features}")

Número de features: 5

1. Calcule a correlação entre as variáveis independentes (AT, V, AP, RH) e a variável dependente (PE). Quais
variáveis parecem ter maior influência na produção de energia?

In [12]:
correlacoes = dados[["AT", "V", "AP", "RH", "PE"]].corr()["PE"]
correlacoes

AT   -0.948128
V    -0.869780
AP    0.518429
RH    0.389794
PE    1.000000
Name: PE, dtype: float64